### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by gmcintire** [SonarSoftwareInc/customer_portal#1]
On a clean install I'm noticing a ton of 404 errors in the log including:

"GET /assets/js/vendor/jquery.payment/jquery.payment.min.js HTTP/1.1" 404"
"GET /assets/js/vendor/jquery/jquery-1.12.3.min.js HTTP/1.1" 404
"GET /assets/js/vendor/moment/moment.min.js HTTP/1.1" 404
"GET /assets/js/vendor/jquery.validate/jquery.validate.min.js HTTP/1.1" 404

There also seems to be no server-side validation happening when entering credit card details and hitting submit when using Firefox 66.0.3. It redirects to the main page with no error messages or changes of any kind.

**Comment by SonarSoftware** [comment]
Is this using the docker container or installing the code natively?

**Comment by gmcintire** [comment]
Docker container, following the instructions in README with docker-compose.

**Comment by alectrocute** [comment]
We're sorry you've experienced this bug, @gmcintire. I've fixed the JS-related 404's in #2 and we're looking into the validation issue now. Thank you for your patience.

**Comment by geneccx** [comment]
#2 is now built and should come up live in any deployed instance within the next 5 minutes. Please confirm if the 404s are resolved, and if the validation issues are also solved with that.

**Comment by geneccx** [comment]
Feel free to reopen this issue if you notice any more 404s.

**Comment by gmcintire** [comment]
The validation issue is still present on a freshly deployed instance I set up on DO:
![2019-05-02-p09j8](https://user-images.githubusercontent.com/3772/57087636-1b5e4c80-6cc6-11e9-8341-d3966c8b2edc.png)

Steps to reproduce:
1) Deploy clean install of portal
2) Using the latest Firefox, go to settings page, don't enter anything and hit 'Save Changes'

**Comment by zulandar** [comment]
@gmcintire I just tested clean install and couldn't reproduce your screenshot.

What version of ubuntu are you running? Also have you attempted with clearing your browser cache?

I tested on Ubuntu 16.04 - fresh install - firefox 66.0.3 (64bit)

![image](https://user-images.githubusercontent.com/20810355/57089094-4f873c80-6cc9-11e9-8814-5d85c3fff913.png)

**Comment by gmcintire** [comment]
Weird, it could be a cache issue on my end. I just tried it with the same instance on a different computer in firefox and it worked as it should. Consider this solved :)

**Comment by zulandar** [comment]
Sounds good. I'll leave this resolved.
